In [15]:
import pandas as pd

## Data Import and Exploration

In [16]:
student_dataset = pd.read_csv("dataset/student_performance_data.csv")

In [17]:
student_dataset.columns

Index(['StudentID', 'Age', 'StudyTimeWeekly', 'Absences', 'ParentalSupport',
       'GPA', 'GradeClass'],
      dtype='object')

In [18]:
student_dataset.shape

(2100, 7)

In [19]:
student_dataset.head()

,StudentID,Age,StudyTimeWeekly,Absences,ParentalSupport,GPA,GradeClass
0,1002,18,15.408756,0,1,3.042915,1
1,1003,15,4.210570,26,2,0.112602,4
2,1004,17,10.028829,14,3,2.054218,3
3,1005,17,4.672495,17,3,1.288061,4
4,1006,18,8.191219,0,1,3.084184,1

In [20]:
student_dataset.tail()

,StudentID,Age,StudyTimeWeekly,Absences,ParentalSupport,GPA,GradeClass
2095,3386,16,1.445434,20,3,1.395631,1
2096,3388,18,10.680555,2,4,3.455509,0
2097,3390,16,6.805500,20,2,1.142333,2
2098,3391,16,12.416653,17,2,1.803297,1
2099,3392,16,17.819907,13,2,2.140014,1

### Dataset Overview
The dataset consists of 2,100 student records across 7 features:
- **Personal Detail:** Student ID, Age
- **Study Habits & Parental Involvement:** Weekly Study Hours, Absences, Parental Support Level
- **Academic Performance:** GPA, Grade Class

## Data Cleaning and Quality Control

In [23]:
student_dataset['GradeClass'].dtypes

dtype('O')

In [24]:
student_dataset['GradeClass'] = student_dataset['GradeClass'].replace(
{0:'A', 1:'B', 2:'C', 3:'D', 4:'F'}
)

student_dataset['GradeClass'].dtypes

dtype('O')

The code above has replaced the numerical representation of the grade class to an alphabetical representation. This change also results in the change of the data type from being an integer to an object.